theme: jekyll-theme-cayman

# Name of website
title: Ncurses Package

# Your name to show in the footer
author: Russell Kajouri

# --- List of links in the navigation bar --- #

navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://kajouri.rf.dg"
